import json
import logging
from typing import Dict, Any, List, Optional
import re
import os
import torch
import torch.nn as nn
import torch.optim as optim

logger = logging.getLogger("PPO_Agent")

class DiffParser:
    """
    Handles parsing and applying diff patches generated by the LLM.
    Uses whitespace-insensitive matching to be robust against minor formatting changes.
    """
    @staticmethod
    def apply_patch(original_code: str, search_block: str, replace_block: str) -> str:
        """
        Applies a search-and-replace block to the code.
        Attempts exact match first, then falls back to line-by-line whitespace-insensitive matching.
        """
        # 1. Exact Match Fast Path
        if search_block in original_code:
            return original_code.replace(search_block, replace_block, 1)

        # 2. Robust Whitespace-Insensitive Matching
        search_lines_norm = [line.strip() for line in search_block.splitlines() if line.strip()]
        orig_lines = original_code.splitlines()

        if not search_lines_norm:
            raise ValueError("Empty search block provided.")

        match_start_idx = -1
        match_end_idx = -1

        for i in range(len(orig_lines)):
            # Try to match starting at line i
            search_idx = 0
            curr_idx = i

            while curr_idx < len(orig_lines) and search_idx < len(search_lines_norm):
                if orig_lines[curr_idx].strip() == "":
                    curr_idx += 1
                    continue
                if orig_lines[curr_idx].strip() == search_lines_norm[search_idx]:
                    search_idx += 1
                    curr_idx += 1
                else:
                    break

            if search_idx == len(search_lines_norm):
                # Found a match!
                match_start_idx = i
                match_end_idx = curr_idx
                break

        if match_start_idx == -1:
            logger.error("Diff Patch Failed: Search block not found in original code even with flexible matching.")
            raise ValueError("Search block not found")

        # Replace the matched lines with the new block
        new_lines = orig_lines[:match_start_idx] + replace_block.splitlines() + orig_lines[match_end_idx:]
        return "\n".join(new_lines)

    @staticmethod
    def parse_llm_json(llm_response: str) -> List[Dict[str, str]]:
        """
        Parses the JSON format expected from the LLM agent containing mutations.
        Expected format:
        [
            {"search": "old code", "replace": "new code"}
        ]
        """
        try:
            # Extract JSON from markdown blocks if necessary
            json_str = llm_response
            match = re.search(r'```json\s*(.*?)\s*```', llm_response, re.DOTALL)
            if match:
                json_str = match.group(1)

            patches = json.loads(json_str)
            if not isinstance(patches, list):
                patches = [patches] # Handle single dict response
            return patches
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM patch output: {e}")
            raise ValueError("Invalid JSON patch format")

class PolicyValueNetwork(nn.Module):
    """
    Basic PPO Actor-Critic Network.
    In a fully operational system, this would ingest vectorized state or embeddings of the code.
    For this MVP, it acts as a structured foundation that learns from scalar environment metrics
    to output a continuous "temperature/creativity" signal that guides the LLM mutation sampler.
    """
    def __init__(self, state_dim=5):
        super().__init__()
        # Actor network (Policy)
        self.actor = nn.Sequential(
            nn.Linear(state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid() # Outputs a scalar representing the "action" (e.g., Temperature for LLM sampling)
        )

        # Critic network (Value)
        self.critic = nn.Sequential(
            nn.Linear(state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1) # Predicts expected reward (V-value)
        )

    def forward(self, state):
        action_mean = self.actor(state)
        value = self.critic(state)
        return action_mean, value

class PPOMetaAgent:
    """
    The main agent that interacts with the LLM API to generate code mutations based on state.
    Integrates a PPO-based Policy/Value network to guide the LLM's creativity and learn from rewards.
    """
    def __init__(self, system_prompt: str = "Minimize BPB under 16MB. Modify architecture hyperparameters within GPTConfig like mlp_expansion, depth_loops, lora_rank, qk_gain_init, and muon_lr."):
        self.system_prompt = system_prompt
        self.api_key = os.environ.get("OPENAI_API_KEY")

        if self.api_key:
            logger.info("OpenAI API Key found. Real LLM integration activated.")
            import openai
            self.client = openai.OpenAI(api_key=self.api_key)
        else:
            logger.info("No OpenAI API Key found. Operating in MOCK mode.")
            self.client = None

        # PPO Learning Infrastructure
        self.state_dim = 5 # e.g., current_sota, iteration, oom_flag, memory_size, sprt_aborts
        self.policy_net = PolicyValueNetwork(state_dim=self.state_dim)
        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=1e-3)
        self.gamma = 0.99
        self.eps_clip = 0.2

        # Memory to store PPO rollouts
        self.rollout_memory = []

    def _extract_vector_state(self, env_history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> torch.Tensor:
        """Converts the environment and telemetry into a float tensor for the PPO network."""
        current_sota = 1.0
        memory_size = len(env_history)
        oom_flag = 1.0 if telemetry.get("recent_oom", False) else 0.0
        iteration = telemetry.get("iteration", 0) / 100.0 # Normalize roughly

        if env_history:
            # SOTA BPB is implicitly tracked by finding the min in history
            # Filter out NaNs to prevent tensor explosion
            valid_bpbs = [e.get("final_bpb") for e in env_history if e.get("final_bpb") is not None and not torch.isnan(torch.tensor(e.get("final_bpb")))]
            if valid_bpbs:
                current_sota = min(valid_bpbs)

        state_vec = [current_sota, float(iteration), oom_flag, float(memory_size), 0.0]
        return torch.tensor(state_vec, dtype=torch.float32)

    def _construct_prompt(self, current_best_code: str, history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> str:
        """
        Constructs the massive state vector ($s_t$) prompt for the LLM.
        """
        prompt = f"### SYSTEM CONSTRAINTS\n{self.system_prompt}\n\n"
        prompt += f"### CURRENT BEST CODE (SOTA)\n```python\n{current_best_code}\n```\n\n"

        prompt += "### RECENT EXPERIMENTS HISTORY (Last K=32)\n"
        for exp in history:
            prompt += f"- Patch: {exp.get('patch', 'N/A')}\n"
            prompt += f"  Status: {exp.get('status', 'UNKNOWN')} | BPB: {exp.get('final_bpb', 'N/A')} | Reward: {exp.get('reward', 'N/A')}\n"

        prompt += "\n### TELEMETRY & DIAGNOSTICS\n"
        prompt += json.dumps(telemetry, indent=2)

        prompt += "\n\n### YOUR TASK\nGenerate a JSON array of search/replace patches to mutate the current best code to improve BPB."
        return prompt

    def generate_action(self, current_best_code: str, history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> str:
        """
        Takes the current state, queries the LLM, applies the diff, and returns the new candidate source code.
        """
        prompt = self._construct_prompt(current_best_code, history, telemetry)

        # 1. PPO Policy Pass
        # The actor network learns from past rewards what 'temperature' to sample the LLM at.
        state_tensor = self._extract_vector_state(history, telemetry)
        with torch.no_grad():
            action_mean, state_value = self.policy_net(state_tensor)
            # Sample action (temperature)
            dist = torch.distributions.Normal(action_mean, 0.1)
            action_temp = dist.sample()
            llm_temperature = torch.clamp(action_temp, 0.1, 1.5).item()
            log_prob = dist.log_prob(action_temp)

        # Store for PPO update later
        self.rollout_memory.append({
            "state": state_tensor,
            "action": action_temp,
            "log_prob": log_prob,
            "value": state_value
        })

        logger.info(f"Querying Meta-Learner LLM (PPO Guided Temp: {llm_temperature:.2f})...")

        llm_response = ""
        if self.client:
            # ACTUAL LLM CALL
            try:
                response = self.client.chat.completions.create(
                    model="gpt-4o",
                    messages=[
                        {"role": "system", "content": "You are a code-mutating PPO agent optimized to output JSON diff patches."},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=llm_temperature
                )
                llm_response = response.choices[0].message.content
            except Exception as e:
                logger.error(f"OpenAI API call failed: {e}")
                return current_best_code
        else:
            # MOCK LLM CALL
            llm_response = '''
            ```json
            [
                {
                    "search": "mlp_expansion = 3",
                    "replace": "mlp_expansion = 4"
                }
            ]
            ```
            '''

        try:
            patches = DiffParser.parse_llm_json(llm_response)
            new_code = current_best_code
            for patch in patches:
                new_code = DiffParser.apply_patch(new_code, patch["search"], patch["replace"])

            logger.info("Successfully applied generated patch.")
            return new_code

        except ValueError as e:
            logger.error(f"Action generation failed during patching: {e}")
            return current_best_code # Fallback to SOTA

    def update_policy(self, final_reward: float):
        """
        Performs the PPO network update using the collected rollout and the environment reward.
        """
        if not self.rollout_memory:
            return

        # Guard against NaN rewards breaking the network weights
        if torch.isnan(torch.tensor(final_reward)):
            logger.warning("Reward is NaN. Skipping PPO Policy Update.")
            self.rollout_memory = []
            return

        # Get latest rollout
        rollout = self.rollout_memory[-1]
        state = rollout["state"]
        action = rollout["action"]
        old_log_prob = rollout["log_prob"]
        old_value = rollout["value"]

        # Calculate Advantage (A_t = R_t - V(s_t))
        reward_tensor = torch.tensor([final_reward], dtype=torch.float32)
        advantage = reward_tensor - old_value.detach()

        # PPO Update (Simplified 1-step update for MVP)
        self.optimizer.zero_grad()

        # New evaluation
        action_mean, new_value = self.policy_net(state)
        dist = torch.distributions.Normal(action_mean, 0.1)
        new_log_prob = dist.log_prob(action)

        # Ratio
        ratio = torch.exp(new_log_prob - old_log_prob.detach())

        # Surrogate Loss
        surr1 = ratio * advantage
        surr2 = torch.clamp(ratio, 1 - self.eps_clip, 1 + self.eps_clip) * advantage
        actor_loss = -torch.min(surr1, surr2)

        # Critic Loss
        critic_loss = nn.MSELoss()(new_value, reward_tensor)

        # Total Loss
        loss = actor_loss + 0.5 * critic_loss
        loss.backward()

        # Clip gradients to prevent explosion
        torch.nn.utils.clip_grad_norm_(self.policy_net.parameters(), max_norm=1.0)
        self.optimizer.step()

        logger.info(f"PPO Policy Updated. Actor Loss: {actor_loss.item():.4f}, Critic Loss: {critic_loss.item():.4f}")

        # Clear memory after update (Since we do step-by-step updates here)
        self.rollout_memory = []

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    agent = PPOMetaAgent()

    dummy_code = """
class GPTConfig:
    # Architecture Hyperparameters
    mlp_expansion = 3
    depth_loops = 3
    """

    search_str = "    mlp_expansion = 3"
    replace_str = "    mlp_expansion = 4"

    print("Testing Robust Diff Parser...")
    new_c = DiffParser.apply_patch(dummy_code, search_str, replace_str)
    print("Success. Mutated Code:")
    print(new_c.strip())
