import json
import logging
from typing import Dict, Any, List, Optional
import re
import os
import torch
import torch.nn as nn
import torch.optim as optim
import ast

logger = logging.getLogger("PPO_Agent")

class ASTDiffParser:
    """
    Handles parsing and applying diff patches generated by the LLM using AST and structural node location.
    Provides safety against minor formatting changes and explicitly handles assignments or class modifications.
    """
    @staticmethod
    def apply_patch(original_code: str, search_block: str, replace_block: str) -> str:
        # Try AST Match first for simple assignments (e.g. Hyperparameter changes)
        try:
            search_tree = ast.parse(search_block)
            if len(search_tree.body) == 1 and isinstance(search_tree.body[0], ast.Assign):
                target_var = search_tree.body[0].targets[0].id

                # Parse full original code to find the exact line number of this variable assignment
                orig_tree = ast.parse(original_code)
                for node in ast.walk(orig_tree):
                    if isinstance(node, ast.Assign) and len(node.targets) == 1 and hasattr(node.targets[0], 'id'):
                        if node.targets[0].id == target_var:
                            # Found the line! Replace it precisely
                            lines = original_code.splitlines()
                            lines[node.lineno - 1] = replace_block.strip()
                            return "\n".join(lines)
        except Exception as e:
            logger.debug(f"AST-based assignment diff failed or wasn't applicable, trying structure matching: {e}")
            pass

        # Use AST based generic patch application
        try:
            # We attempt to find matching nodes in the original AST that structurally match the search block
            search_ast = ast.parse(search_block)
            original_ast = ast.parse(original_code)

            # Simple heuristic: if the search block is a single function/class def, try to find it by name
            if len(search_ast.body) == 1 and isinstance(search_ast.body[0], (ast.FunctionDef, ast.ClassDef)):
                target_name = search_ast.body[0].name
                for node in original_ast.body:
                    if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name == target_name:
                        # Before replacing, verify that the found node actually matches the search block's content
                        start_line = node.lineno - 1
                        end_line = node.end_lineno
                        lines = original_code.splitlines()
                        original_node_text = "\n".join(lines[start_line:end_line])

                        # Verify using robust whitespace-insensitive match to ensure we are replacing the right code
                        search_lines_norm = [line.strip() for line in search_block.splitlines() if line.strip()]
                        orig_node_lines_norm = [line.strip() for line in original_node_text.splitlines() if line.strip()]

                        # Only proceed if the original node matches the search block structurally
                        # This avoids replacing a class when the LLM hallucinated its current state
                        if search_lines_norm == orig_node_lines_norm:
                            new_lines = lines[:start_line] + replace_block.splitlines() + lines[end_line:]
                            return "\n".join(new_lines)
                        else:
                            raise ValueError(f"AST structural match found node {target_name}, but its content does not match the search block.")

            # More general AST structure matching could be implemented here,
            # but standard AST modules don't provide easy arbitrary block replacement
            # while maintaining exact formatting for the rest of the file.
        except Exception as e:
            logger.debug(f"AST-based structural diff failed, falling back to text match: {e}")

        # Fallback: Robust Whitespace-Insensitive Matching
        return ASTDiffParser._apply_text_patch(original_code, search_block, replace_block)

    @staticmethod
    def _apply_text_patch(original_code: str, search_block: str, replace_block: str) -> str:
        # 1. Exact Match Fast Path
        if search_block in original_code:
            return original_code.replace(search_block, replace_block, 1)

        # 2. Robust Whitespace-Insensitive Matching
        search_lines_norm = [line.strip() for line in search_block.splitlines() if line.strip()]
        orig_lines = original_code.splitlines()

        if not search_lines_norm:
            raise ValueError("Empty search block provided.")

        match_start_idx = -1
        match_end_idx = -1

        for i in range(len(orig_lines)):
            search_idx = 0
            curr_idx = i

            while curr_idx < len(orig_lines) and search_idx < len(search_lines_norm):
                if orig_lines[curr_idx].strip() == "":
                    curr_idx += 1
                    continue
                if orig_lines[curr_idx].strip() == search_lines_norm[search_idx]:
                    search_idx += 1
                    curr_idx += 1
                else:
                    break

            if search_idx == len(search_lines_norm):
                match_start_idx = i
                match_end_idx = curr_idx
                break

        if match_start_idx == -1:
            logger.error("Diff Patch Failed: Search block not found in original code even with flexible matching.")
            raise ValueError("Search block not found")

        new_lines = orig_lines[:match_start_idx] + replace_block.splitlines() + orig_lines[match_end_idx:]
        return "\n".join(new_lines)

    @staticmethod
    def parse_llm_json(llm_response: str) -> List[Dict[str, str]]:
        try:
            json_str = llm_response
            match = re.search(r'```json\s*(.*?)\s*```', llm_response, re.DOTALL)
            if match:
                json_str = match.group(1)

            patches = json.loads(json_str)
            if not isinstance(patches, list):
                patches = [patches]

            # Schema validation
            for patch in patches:
                if not isinstance(patch, dict) or 'search' not in patch or 'replace' not in patch:
                    raise ValueError("Patch missing 'search' or 'replace' keys.")
                if not isinstance(patch['search'], str) or not isinstance(patch['replace'], str):
                    raise ValueError("Patch 'search' and 'replace' values must be strings.")

            return patches
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM patch output: {e}")
            raise ValueError("Invalid JSON patch format")


class PolicyValueNetwork(nn.Module):
    """
    Basic PPO Actor-Critic Network handling an extended state vector.
    """
    def __init__(self, state_dim=13):
        super().__init__()
        self.actor = nn.Sequential(
            nn.Linear(state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )
        self.critic = nn.Sequential(
            nn.Linear(state_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, state):
        action_mean = self.actor(state)
        value = self.critic(state)
        return action_mean, value

class PPOMetaAgent:
    def __init__(self, system_prompt: str = "Minimize BPB under 16MB. Modify architecture hyperparameters within GPTConfig like mlp_expansion, depth_loops, lora_rank, qk_gain_init, and muon_lr."):
        self.system_prompt = system_prompt
        self.api_key = os.environ.get("OPENAI_API_KEY")

        if self.api_key:
            logger.info("OpenAI API Key found. Real LLM integration activated.")
            import openai
            self.client = openai.OpenAI(api_key=self.api_key)
        else:
            logger.info("No OpenAI API Key found. Operating in MOCK mode.")
            self.client = None

        self.state_dim = 13
        self.policy_net = PolicyValueNetwork(state_dim=self.state_dim)
        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=1e-3)
        self.gamma = 0.99
        self.eps_clip = 0.2
        self.rollout_memory = []

    def _extract_vector_state(self, current_code: str, env_history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> torch.Tensor:
        """
        Builds a rich state vector.
        Features: SOTA BPB, Iteration, Memory Size, OOM Flag, Recent Delta Trend, SPRT Abort Freq, Extracted AST Params.
        """
        current_sota = 1.0
        memory_size = len(env_history)
        oom_flag = 1.0 if telemetry.get("recent_oom", False) else 0.0
        iteration = telemetry.get("iteration", 0) / 100.0

        # Parse current code for Hyperparams
        lora_rank_val = 0.0
        mlp_exp_val = 0.0
        depth_loops_val = 0.0
        qk_gain_init_val = 0.0
        muon_lr_val = 0.0
        try:
            tree = ast.parse(current_code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Assign) and len(node.targets) == 1 and hasattr(node.targets[0], 'id'):
                    if node.targets[0].id == "lora_rank" and isinstance(node.value, ast.Constant):
                        lora_rank_val = float(node.value.value)
                    if node.targets[0].id == "mlp_expansion" and isinstance(node.value, ast.Constant):
                        mlp_exp_val = float(node.value.value)
                    if node.targets[0].id == "depth_loops" and isinstance(node.value, ast.Constant):
                        depth_loops_val = float(node.value.value)
                    if node.targets[0].id == "qk_gain_init" and isinstance(node.value, ast.Constant):
                        qk_gain_init_val = float(node.value.value)
                    if node.targets[0].id == "muon_lr" and isinstance(node.value, ast.Constant):
                        muon_lr_val = float(node.value.value)
        except: pass

        # Calculate Trends
        abort_freq = 0.0
        delta_trend = 0.0
        avg_abort_step = 0.0
        if env_history:
            valid_bpbs = [e.get("final_bpb") for e in env_history if e.get("final_bpb") is not None and not torch.isnan(torch.tensor(e.get("final_bpb")))]
            if valid_bpbs:
                current_sota = min(valid_bpbs)

            # Abort freq and avg abort step
            aborts = [e for e in env_history if e.get("status") == "ABORTED"]
            abort_freq = len(aborts) / float(max(1, len(env_history)))

            if aborts:
                avg_abort_step = sum([e.get("components", {}).get("sprt_abort_penalty", 0.0) for e in aborts]) / len(aborts)

            # Reward Trend
            recent_rewards = [e.get("reward", 0.0) for e in env_history[-3:]]
            if recent_rewards:
                delta_trend = sum(recent_rewards) / len(recent_rewards)

        state_vec = [
            current_sota, float(iteration), oom_flag, float(memory_size),
            abort_freq, delta_trend, lora_rank_val, mlp_exp_val,
            depth_loops_val, qk_gain_init_val, muon_lr_val, avg_abort_step,
            float(len(env_history) > 0 and any("causality" in e.get("components", {}) for e in env_history[-5:]))
        ]
        return torch.tensor(state_vec, dtype=torch.float32)

    def _construct_prompt(self, current_best_code: str, history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> str:
        prompt = f"### SYSTEM CONSTRAINTS\n{self.system_prompt}\n\n"
        prompt += f"### CURRENT BEST CODE (SOTA)\n```python\n{current_best_code}\n```\n\n"
        prompt += "### RECENT EXPERIMENTS HISTORY (Last K=32)\n"
        for exp in history:
            prompt += f"- Patch: {exp.get('patch', 'N/A')}\n"
            prompt += f"  Status: {exp.get('status', 'UNKNOWN')} | BPB: {exp.get('final_bpb', 'N/A')} | Reward: {exp.get('reward', 'N/A')}\n"
            if exp.get('remediation'):
                prompt += f"  Remediation: {exp.get('remediation')}\n"

        prompt += "\n### TELEMETRY & DIAGNOSTICS\n"
        prompt += json.dumps(telemetry, indent=2)
        prompt += "\n\n### YOUR TASK\nGenerate a JSON array of search/replace patches to mutate the current best code to improve BPB."
        return prompt

    def generate_action(self, current_best_code: str, history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> str:
        prompt = self._construct_prompt(current_best_code, history, telemetry)
        state_tensor = self._extract_vector_state(current_best_code, history, telemetry)

        with torch.no_grad():
            action_mean, state_value = self.policy_net(state_tensor)
            dist = torch.distributions.Normal(action_mean, 0.1)
            action_temp = dist.sample()
            llm_temperature = torch.clamp(action_temp, 0.1, 1.5).item()
            log_prob = dist.log_prob(action_temp)

        self.rollout_memory.append({
            "state": state_tensor,
            "action": action_temp,
            "log_prob": log_prob,
            "value": state_value
        })

        logger.info(f"Querying Meta-Learner LLM (PPO Temp: {llm_temperature:.2f} | SPRT Freq: {state_tensor[4]:.2f})...")

        llm_response = ""
        if self.client:
            try:
                response = self.client.chat.completions.create(
                    model="gpt-4o",
                    messages=[
                        {"role": "system", "content": "You are a code-mutating PPO agent optimized to output JSON diff patches."},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=llm_temperature
                )
                llm_response = response.choices[0].message.content
            except Exception as e:
                logger.error(f"OpenAI API call failed: {e}")
                return current_best_code
        else:
            llm_response = '''
            ```json
            [
                {
                    "search": "    mlp_expansion = 3",
                    "replace": "    mlp_expansion = 4"
                }
            ]
            ```
            '''

        try:
            patches = ASTDiffParser.parse_llm_json(llm_response)
            new_code = current_best_code
            for patch in patches:
                new_code = ASTDiffParser.apply_patch(new_code, patch["search"], patch["replace"])

            # AST-preserving transform validation
            ast.parse(new_code)

            logger.info("Successfully applied generated patch.")
            return new_code

        except (ValueError, SyntaxError) as e:
            logger.error(f"Action generation failed during patching or syntax validation: {e}")
            return current_best_code

    def update_policy(self, final_reward: float):
        if not self.rollout_memory:
            return

        if torch.isnan(torch.tensor(final_reward)):
            logger.warning("Reward is NaN. Skipping PPO Policy Update.")
            self.rollout_memory = []
            return

        rollout = self.rollout_memory[-1]
        state = rollout["state"]
        action = rollout["action"]
        old_log_prob = rollout["log_prob"]
        old_value = rollout["value"]

        reward_tensor = torch.tensor([final_reward], dtype=torch.float32)
        advantage = reward_tensor - old_value.detach()

        self.optimizer.zero_grad()

        action_mean, new_value = self.policy_net(state)
        dist = torch.distributions.Normal(action_mean, 0.1)
        new_log_prob = dist.log_prob(action)

        ratio = torch.exp(new_log_prob - old_log_prob.detach())
        surr1 = ratio * advantage
        surr2 = torch.clamp(ratio, 1 - self.eps_clip, 1 + self.eps_clip) * advantage
        actor_loss = -torch.min(surr1, surr2)
        critic_loss = nn.MSELoss()(new_value, reward_tensor)

        loss = actor_loss + 0.5 * critic_loss
        loss.backward()

        torch.nn.utils.clip_grad_norm_(self.policy_net.parameters(), max_norm=1.0)
        self.optimizer.step()

        logger.info(f"PPO Policy Updated. Actor Loss: {actor_loss.item():.4f}, Critic Loss: {critic_loss.item():.4f}")
        self.rollout_memory = []

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    dummy_code = """
class GPTConfig:
    # Architecture Hyperparameters
    mlp_expansion = 3
    depth_loops = 3
    lora_rank = 4
    """

    # Test state parsing
    agent = PPOMetaAgent()
    state = agent._extract_vector_state(dummy_code, [], {})
    print(f"Extracted Rich State Tensor: {state}")
