import json
import logging
from typing import Dict, Any, List, Optional
import re
import os

logger = logging.getLogger("PPO_Agent")

class DiffParser:
    """
    Handles parsing and applying diff patches generated by the LLM.
    Uses whitespace-insensitive matching to be robust against minor formatting changes.
    """
    @staticmethod
    def apply_patch(original_code: str, search_block: str, replace_block: str) -> str:
        """
        Applies a search-and-replace block to the code.
        Attempts exact match first, then falls back to line-by-line whitespace-insensitive matching.
        """
        # 1. Exact Match Fast Path
        if search_block in original_code:
            return original_code.replace(search_block, replace_block, 1)

        # 2. Robust Whitespace-Insensitive Matching
        search_lines_norm = [line.strip() for line in search_block.splitlines() if line.strip()]
        orig_lines = original_code.splitlines()

        if not search_lines_norm:
            raise ValueError("Empty search block provided.")

        match_start_idx = -1
        match_end_idx = -1

        for i in range(len(orig_lines)):
            # Try to match starting at line i
            search_idx = 0
            curr_idx = i

            while curr_idx < len(orig_lines) and search_idx < len(search_lines_norm):
                if orig_lines[curr_idx].strip() == "":
                    curr_idx += 1
                    continue
                if orig_lines[curr_idx].strip() == search_lines_norm[search_idx]:
                    search_idx += 1
                    curr_idx += 1
                else:
                    break

            if search_idx == len(search_lines_norm):
                # Found a match!
                match_start_idx = i
                match_end_idx = curr_idx
                break

        if match_start_idx == -1:
            logger.error("Diff Patch Failed: Search block not found in original code even with flexible matching.")
            raise ValueError("Search block not found")

        # Replace the matched lines with the new block
        new_lines = orig_lines[:match_start_idx] + replace_block.splitlines() + orig_lines[match_end_idx:]
        return "\n".join(new_lines)

    @staticmethod
    def parse_llm_json(llm_response: str) -> List[Dict[str, str]]:
        """
        Parses the JSON format expected from the LLM agent containing mutations.
        Expected format:
        [
            {"search": "old code", "replace": "new code"}
        ]
        """
        try:
            # Extract JSON from markdown blocks if necessary
            json_str = llm_response
            match = re.search(r'```json\s*(.*?)\s*```', llm_response, re.DOTALL)
            if match:
                json_str = match.group(1)

            patches = json.loads(json_str)
            if not isinstance(patches, list):
                patches = [patches] # Handle single dict response
            return patches
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM patch output: {e}")
            raise ValueError("Invalid JSON patch format")

class PPOMetaAgent:
    """
    The main agent that interacts with the LLM API to generate code mutations based on state.
    """
    def __init__(self, system_prompt: str = "program.md"):
        self.system_prompt = system_prompt
        self.api_key = os.environ.get("OPENAI_API_KEY")

        if self.api_key:
            logger.info("OpenAI API Key found. Real LLM integration activated.")
            import openai
            self.client = openai.OpenAI(api_key=self.api_key)
        else:
            logger.info("No OpenAI API Key found. Operating in MOCK mode.")
            self.client = None

    def _construct_prompt(self, current_best_code: str, history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> str:
        """
        Constructs the massive state vector ($s_t$) prompt for the LLM.
        """
        prompt = f"### SYSTEM CONSTRAINTS\n{self.system_prompt}\n\n"
        prompt += f"### CURRENT BEST CODE (SOTA)\n```python\n{current_best_code}\n```\n\n"

        prompt += "### RECENT EXPERIMENTS HISTORY (Last K=32)\n"
        for exp in history:
            prompt += f"- Patch: {exp.get('patch', 'N/A')}\n"
            prompt += f"  Status: {exp.get('status', 'UNKNOWN')} | BPB: {exp.get('final_bpb', 'N/A')} | Reward: {exp.get('reward', 'N/A')}\n"

        prompt += "\n### TELEMETRY & DIAGNOSTICS\n"
        prompt += json.dumps(telemetry, indent=2)

        prompt += "\n\n### YOUR TASK\nGenerate a JSON array of search/replace patches to mutate the current best code to improve BPB."
        return prompt

    def generate_action(self, current_best_code: str, history: List[Dict[str, Any]], telemetry: Dict[str, Any]) -> str:
        """
        Takes the current state, queries the LLM, applies the diff, and returns the new candidate source code.
        """
        prompt = self._construct_prompt(current_best_code, history, telemetry)

        logger.info("Querying Meta-Learner LLM for next action...")

        llm_response = ""
        if self.client:
            # ACTUAL LLM CALL
            try:
                response = self.client.chat.completions.create(
                    model="gpt-4o",
                    messages=[
                        {"role": "system", "content": "You are a code-mutating PPO agent optimized to output JSON diff patches."},
                        {"role": "user", "content": prompt}
                    ],
                    temperature=0.7
                )
                llm_response = response.choices[0].message.content
            except Exception as e:
                logger.error(f"OpenAI API call failed: {e}")
                return current_best_code
        else:
            # MOCK LLM CALL
            llm_response = '''
            ```json
            [
                {
                    "search": "hidden_dim = 3 * config.n_embd",
                    "replace": "hidden_dim = 4 * config.n_embd"
                }
            ]
            ```
            '''

        try:
            patches = DiffParser.parse_llm_json(llm_response)
            new_code = current_best_code
            for patch in patches:
                new_code = DiffParser.apply_patch(new_code, patch["search"], patch["replace"])

            logger.info("Successfully applied generated patch.")
            return new_code

        except ValueError as e:
            logger.error(f"Action generation failed during patching: {e}")
            return current_best_code # Fallback to SOTA

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    agent = PPOMetaAgent(system_prompt="Minimize BPB under 16MB.")

    dummy_code = """
class MLP3x(nn.Module):
    def __init__(self, config):
        super().__init__()

        # 3x expansion instead of standard 4x (e.g., 512 -> 1536)
        hidden_dim = 3 * config.n_embd
    """

    # Intentionally mismatched whitespace to test robustness
    search_str = """
    # 3x expansion instead of standard 4x (e.g., 512 -> 1536)
    hidden_dim = 3 * config.n_embd
    """
    replace_str = "        # Expanded\n        hidden_dim = 4 * config.n_embd"

    print("Testing Robust Diff Parser...")
    new_c = DiffParser.apply_patch(dummy_code, search_str, replace_str)
    print("Success. Mutated Code:")
    print(new_c.strip())
